version: '3'

services:
  line-provider:
    build:
      context: ../line-provider
    ports:
      - "8000:8000"

  bet-maker:
    build:
      context: .
    ports:
      - "8001:8001"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
